import { crudActionTypes } from '../COMMON/crud/actionTypes';
/**
 * Action Types for dispatch of Users state
 */
export const  ACTION_TYPES  = {...{
    REFUND: 'ORDERS_REFUND',
    REFUND_SUCCESS: 'ORDERS_REFUND_SUCCESS',
    REFUND_FAILED: 'ORDERS_REFUND_FAILED',

    SEND_MONEY: 'ORDERS_SEND_MONEY',
    SEND_MONEY_SUCCESS: 'ORDERS_SEND_MONEY_SUCCESS',
    SEND_MONEY_FAILED: 'ORDERS_SEND_MONEY_FAILED',

    GET_REFUNDABLE_NUMBER: 'ORDERS_GET_REFUNDABLE_NUMBER',
    GET_REFUNDABLE_NUMBER_SUCCESS: 'ORDERS_GET_REFUNDABLE_NUMBER_SUCCESS',
    GET_REFUNDABLE_NUMBER_FAILED: 'ORDERS_GET_REFUNDABLE_NUMBER_FAILED',
    //Custom Action Types
    },...crudActionTypes('ORDERS')};

