import {LangState} from "@/app-redux/lang/model";
import {ProfileState} from "@/app-redux/profile/model";
import {UsersState} from "@/app-redux/users/model";
import {CrudExampleState} from "@/app-redux/crudExample/model";
import {StaticPageState} from "@/app-redux/staticPages/model";
import {ManufacturerState} from "./manufacturers/model";
import {AuthState} from "@/app-redux/auth/model";
import { VehicleTypesState } from "./vehicleTypes/model";
import { RolesState } from "./roles/model";
import { VehiclesState } from "./vehicles/model";
import { ServicesState } from "./services/model";
import { ProvidersState } from "./providers/model";
import { SettingState } from "./settings/model";
import { OrdersState } from "./orders/model";
import { CitiesState } from "./cities/model";
import { CityZonesState } from "./cityZones/model";
import { ReviewsState } from "./reviews/model";
import { ContactUsState } from "./contactUs/model";
import { CleanerReportsState } from './reportsCleaner/model';
import { ServiceReportsState } from './reportsService/model';
import { WithdrawalsState } from './withdrawals/model';
import { OrdersGraphState } from './dashboard/model';

export interface AppState {
    auth: AuthState;
    cities: CitiesState;
    cityZones: CityZonesState;
    crudExample: CrudExampleState;
    lang: LangState;
    manufacturers: ManufacturerState;
    orders: OrdersState;
    profile: ProfileState;
    providers: ProvidersState;
    reviews: ReviewsState;
    roles: RolesState;
    services: ServicesState;
    settings: SettingState;
    staticPages: StaticPageState;
    users: UsersState;
    vehicles: VehiclesState;
    vehicleTypes: VehicleTypesState;
    contactUs: ContactUsState;
    reportsCleaner: CleanerReportsState;
    reportsService: ServiceReportsState;
    withdrawals: WithdrawalsState;
    ordersGraph: OrdersGraphState;
}
