/**
 * Action Types for dispatch of Auth state
 */
export const  ACTION_TYPES  = {
  //Token
  GET_OAUTH_TOKEN                   : 'GET_OAUTH_TOKEN',
  GET_OAUTH_TOKEN_SUCCESS           : 'GET_OAUTH_TOKEN_SUCCESS',
  GET_OAUTH_TOKEN_ERROR             : 'GET_OAUTH_TOKEN_ERROR',

  //Login
  AUTH_LOGIN                        : 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS                : 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_ERROR                  : 'AUTH_LOGIN_ERROR',

  //Registration
  AUTH_REGISTER                     : 'AUTH_REGISTER',
  AUTH_REGISTER_SUCCESS             : 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_ERROR               : 'AUTH_REGISTER_ERROR',

  AUTH_VERIFICATION_EMAIL           : 'AUTH_VERIFICATION_EMAIL',
  AUTH_VERIFICATION_EMAIL_SUCCESS   : 'AUTH_VERIFICATION_EMAIL_SUCCESS',
  AUTH_VERIFICATION_EMAIL_ERROR     : 'AUTH_VERIFICATION_EMAIL_ERROR',

  RESEND_VERIFICATION_EMAIL         : 'RESEND_VERIFICATION_EMAIL',
  RESEND_VERIFICATION_EMAIL_SUCCESS : 'RESEND_VERIFICATION_EMAIL_SUCCESS',
  RESEND_VERIFICATION_EMAIL_ERROR   : 'RESEND_VERIFICATION_EMAIL_ERROR',

  //Reset password
  RESET_PASS_EMAIL                  : 'RESET_PASS_EMAIL',
  RESET_PASS_EMAIL_SUCCESS          : 'RESET_PASS_EMAIL_SUCCESS',
  RESET_PASS_EMAIL_ERROR            : 'RESET_PASS_EMAIL_ERROR',

  RESET_PASS_UPDATE                 : 'RESET_PASS_UPDATE',
  RESET_PASS_UPDATE_SUCCESS         : 'RESET_PASS_UPDATE_SUCCESS',
  RESET_PASS_UPDATE_ERROR           : 'RESET_PASS_UPDATE_ERROR',

  //Logout
  LOGOUT                            : 'LOGOUT',
};
