export enum REPORTS_CLEANER_RELATIONS {
  TRANSLATIONS = 'translations',
  AVATAR = 'avatar',
  PHOTOS = 'photos',
  USER = 'user',
  USER_AVATAR = 'user.avatar',
  CONTACTS = 'contacts',
  SERVICES = 'services',
  WORKSHOP_SERVICES = 'workshopServices',
  WORKSHOP_SERVICES_VEHICLE_TYPES = 'workshopServices.vehicleTypes',
  CITY_ZONES = 'cityZones',
  CITY_ZONES_CITY = 'cityZones.city',
  SERVICES_VEHICLE_TYPES = 'services.vehicleTypes',
  SCHEDULES = 'schedules',
  SCHEDULE_DAY_OFFS = 'scheduleDayOffs',
  WALLET = 'wallet',
  ACTIVE_ORDER = 'activeOrder',
}